#!/bin/sh

append_to_bash_profile() {
    echo "$1" >> ~/.bash_profile
}

if ! command -v xcode-select >/dev/null; then
    echo "Looks like we need to install xcode cli tools..."

    xcode-select --install
fi

if ! command -v brew >/dev/null; then
    echo "Installing Homebrew ..."

    curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
fi

brew tap caskroom/cask

# Programs

echo "Lets install some software..."

brew cask install virtualbox
brew cask install slack
brew cask install lastpass
brew cask install docker
brew cask install vagrant

# Languages

echo "Lets add some language, but first some version managers..."

brew install rbenv
brew install ruby-build

# shellcheck disable=SC2016
append_to_bash_profile 'eval "$(rbenv init -)"'

brew install nvm
brew install npm

# shellcheck disable=SC2016
append_to_bash_profile 'export NVM_DIR="$HOME/.nvm"'
# shellcheck disable=SC2016
append_to_bash_profile '  . "$(brew --prefix nvm)/nvm.sh"'

echo 'Setting up Ruby'

find_latest_ruby() {
  rbenv install -l | grep -v - | tail -1 | sed -e 's/^ *//'
}

ruby_version="$(find_latest_ruby)"

rbenv install -s "$ruby_version"

echo 'Lets set up Vagrant now'

cd ~ || exit

git clone https://github.com/madetech/vagrant-dev.git

cd ./vagrant-dev || exit

echo "$ruby_version" >> .ruby-version

gem install bundler
gem install librarian
gem install librarian-chef

librarian-chef install

vagrant plugin install vagrant-omnibus

vagrant up

vagrant provision

echo ''
echo 'Now your good to go! And welcome to MadeTech'

